//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicLINQWebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Player", Namespace="http://schemas.datacontract.org/2004/07/ClinicLINQWebApp")]
    [System.SerializableAttribute()]
    public partial class Player : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((this.PhoneNumberField.Equals(value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationID {
            get {
                return this.RegistrationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationIDField, value) != true)) {
                    this.RegistrationIDField = value;
                    this.RaisePropertyChanged("RegistrationID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Club", Namespace="http://schemas.datacontract.org/2004/07/ClinicLINQWebApp")]
    [System.SerializableAttribute()]
    public partial class Club : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FoundedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WorldRankingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Founded {
            get {
                return this.FoundedField;
            }
            set {
                if ((this.FoundedField.Equals(value) != true)) {
                    this.FoundedField = value;
                    this.RaisePropertyChanged("Founded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationID {
            get {
                return this.RegistrationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationIDField, value) != true)) {
                    this.RegistrationIDField = value;
                    this.RaisePropertyChanged("RegistrationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WorldRanking {
            get {
                return this.WorldRankingField;
            }
            set {
                if ((this.WorldRankingField.Equals(value) != true)) {
                    this.WorldRankingField = value;
                    this.RaisePropertyChanged("WorldRanking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Membership", Namespace="http://schemas.datacontract.org/2004/07/ClinicLINQWebApp")]
    [System.SerializableAttribute()]
    public partial class Membership : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClubIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MembershipIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumOfGamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubID {
            get {
                return this.ClubIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ClubIDField, value) != true)) {
                    this.ClubIDField = value;
                    this.RaisePropertyChanged("ClubID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipID {
            get {
                return this.MembershipIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MembershipIDField, value) != true)) {
                    this.MembershipIDField = value;
                    this.RaisePropertyChanged("MembershipID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumOfGames {
            get {
                return this.NumOfGamesField;
            }
            set {
                if ((this.NumOfGamesField.Equals(value) != true)) {
                    this.NumOfGamesField = value;
                    this.RaisePropertyChanged("NumOfGames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerID {
            get {
                return this.PlayerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerIDField, value) != true)) {
                    this.PlayerIDField = value;
                    this.RaisePropertyChanged("PlayerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILINQDatabaseService")]
    public interface ILINQDatabaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/PlayerRegistration", ReplyAction="http://tempuri.org/ILINQDatabaseService/PlayerRegistrationResponse")]
        bool PlayerRegistration(ClinicLINQWebApp.ServiceReference1.Player player);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/ClubRegistration", ReplyAction="http://tempuri.org/ILINQDatabaseService/ClubRegistrationResponse")]
        bool ClubRegistration(ClinicLINQWebApp.ServiceReference1.Club club);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/GetPlayerInfo", ReplyAction="http://tempuri.org/ILINQDatabaseService/GetPlayerInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/ILINQDatabaseService/GetPlayerInfoFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        ClinicLINQWebApp.ServiceReference1.Player GetPlayerInfo(string firstname, string lastname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/GetClubInfo", ReplyAction="http://tempuri.org/ILINQDatabaseService/GetClubInfoResponse")]
        ClinicLINQWebApp.ServiceReference1.Club GetClubInfo(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/NewMembership", ReplyAction="http://tempuri.org/ILINQDatabaseService/NewMembershipResponse")]
        bool NewMembership(string fullname, string clubname, System.DateTime startdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/GetMembership", ReplyAction="http://tempuri.org/ILINQDatabaseService/GetMembershipResponse")]
        ClinicLINQWebApp.ServiceReference1.Membership GetMembership(string fullname, string clubname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILINQDatabaseService/UpdateMembership", ReplyAction="http://tempuri.org/ILINQDatabaseService/UpdateMembershipResponse")]
        bool UpdateMembership(string fullname, string clubname, System.DateTime enddate, int gamesplayed);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILINQDatabaseServiceChannel : ClinicLINQWebApp.ServiceReference1.ILINQDatabaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LINQDatabaseServiceClient : System.ServiceModel.ClientBase<ClinicLINQWebApp.ServiceReference1.ILINQDatabaseService>, ClinicLINQWebApp.ServiceReference1.ILINQDatabaseService {
        
        public LINQDatabaseServiceClient() {
        }
        
        public LINQDatabaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LINQDatabaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LINQDatabaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LINQDatabaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PlayerRegistration(ClinicLINQWebApp.ServiceReference1.Player player) {
            return base.Channel.PlayerRegistration(player);
        }
        
        public bool ClubRegistration(ClinicLINQWebApp.ServiceReference1.Club club) {
            return base.Channel.ClubRegistration(club);
        }
        
        public ClinicLINQWebApp.ServiceReference1.Player GetPlayerInfo(string firstname, string lastname) {
            return base.Channel.GetPlayerInfo(firstname, lastname);
        }
        
        public ClinicLINQWebApp.ServiceReference1.Club GetClubInfo(string name) {
            return base.Channel.GetClubInfo(name);
        }
        
        public bool NewMembership(string fullname, string clubname, System.DateTime startdate) {
            return base.Channel.NewMembership(fullname, clubname, startdate);
        }
        
        public ClinicLINQWebApp.ServiceReference1.Membership GetMembership(string fullname, string clubname) {
            return base.Channel.GetMembership(fullname, clubname);
        }
        
        public bool UpdateMembership(string fullname, string clubname, System.DateTime enddate, int gamesplayed) {
            return base.Channel.UpdateMembership(fullname, clubname, enddate, gamesplayed);
        }
    }
}
